# Generated by Django 4.1.3 on 2022-11-24 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(max_length=30, verbose_name='Código')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('serial', models.CharField(max_length=50, verbose_name='Serial')),
                ('fix_active', models.CharField(max_length=50, verbose_name='Activo Fijo')),
                ('maker', models.CharField(max_length=100, verbose_name='Fabricante')),
                ('date_manufactured', models.DateField(verbose_name='Fecha de Fabricación')),
                ('date_entry', models.DateField(verbose_name='Fecha de Ingreso')),
                ('use_time', models.PositiveSmallIntegerField(verbose_name='Tiempo de Uso')),
                ('manufacturer_manual', models.FileField(blank=True, null=True, upload_to='', verbose_name='Manual de Fabricante')),
                ('manufacturer_docs', models.FileField(blank=True, null=True, upload_to='', verbose_name='Documentos Anexos de Fabricante')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('frequency_maintenance', models.SmallIntegerField(choices=[(3, 3), (6, 6), (9, 9), (12, 12), (18, 18), (24, 24)], verbose_name='Frecuencia Mantenimiento')),
                ('calibration', models.BooleanField(default=True, verbose_name='Requiere Calibración?')),
                ('frequency_calibration', models.SmallIntegerField(blank=True, choices=[(3, 3), (6, 6), (9, 9), (12, 12), (18, 18), (24, 24)], null=True, verbose_name='Frecuencia Calibración')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipments',
                'db_table': 'Equipment',
            },
        ),
    ]
