# Generated by Django 4.1.3 on 2022-11-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='calibration',
            field=models.BooleanField(default=False, verbose_name='Requiere Calibración?'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer_docs',
            field=models.FileField(blank=True, null=True, upload_to='equipment_docs/%Y%m%d', verbose_name='Documentos Anexos de Fabricante'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer_manual',
            field=models.FileField(blank=True, null=True, upload_to='equipment_manual/%Y%m%d', verbose_name='Manual de Fabricante'),
        ),
    ]
