# Generated by Django 4.1.3 on 2022-11-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipment_calibration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='use_time',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tiempo de Uso'),
        ),
    ]
