# Generated by Django 4.1.3 on 2022-12-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_alter_equipment_use_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ubicación'),
        ),
    ]
