# Generated by Django 4.1.3 on 2022-12-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_equipment_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='frequency_calibration',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Frecuencia Calibración'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='frequency_maintenance',
            field=models.SmallIntegerField(verbose_name='Frecuencia Mantenimiento'),
        ),
    ]
