# Generated by Django 4.1.4 on 2022-12-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_alter_equipment_frequency_calibration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='photo_equipment',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen del Equipo'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='register_regulatory',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Registro Regulatorio'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='frequency_calibration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Frecuencia Calibración'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='frequency_maintenance',
            field=models.PositiveIntegerField(verbose_name='Frecuencia Mantenimiento'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='maker',
            field=models.CharField(max_length=100, verbose_name='Marca/Modelo'),
        ),
    ]
