# Generated by Django 4.1.4 on 2022-12-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_remove_equipment_code_remove_equipment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='photo_equipment',
            field=models.ImageField(blank=True, null=True, upload_to='photo_equipment/%Y%m%d', verbose_name='Imagen del Equipo'),
        ),
    ]
