# Generated by Django 4.1.4 on 2022-12-08 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0006_alter_equipment_frequency_calibration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('certificate_number', models.CharField(max_length=30, verbose_name='Número de Certificado')),
                ('date_calibration', models.DateField(verbose_name='Fecha')),
                ('date_calibration_next', models.DateField(blank=True, null=True)),
                ('calibration_certificate', models.FileField(blank=True, null=True, upload_to='calibration_certificate/%Y%m%d', verbose_name='Certificado de Calibración')),
                ('comments_calibration', models.TextField(verbose_name='Observaciones')),
                ('calibration_made_by', models.CharField(blank=True, max_length=300, null=True, verbose_name='Realizad por')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='equipment.equipment', verbose_name='Equipo')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calibration',
                'verbose_name_plural': 'Calibrations',
                'db_table': 'Calibration',
            },
        ),
    ]
