# Generated by Django 4.1.4 on 2022-12-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='calibration_made_by',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Realizado por'),
        ),
    ]
