# Generated by Django 4.1.3 on 2022-12-04 05:06

import core.maintenance.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0004_alter_equipment_use_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('maintenance_number', models.CharField(default=core.maintenance.models.increment_number_maintenance, max_length=30, verbose_name='')),
                ('maintenance_type', models.CharField(choices=[('Correctivo', 'Correctivo'), ('Preventivo', 'Preventivo')], max_length=30, verbose_name='Tipo de Mantenimiento')),
                ('date_maintenance', models.DateField(verbose_name='Fecha')),
                ('date_maintenance_next', models.DateField()),
                ('physical_record', models.FileField(blank=True, null=True, upload_to='physical_record/%Y%m%d', verbose_name='Registro Físico')),
                ('description_maintenance', models.TextField(verbose_name='Detalle de Mantenimiento')),
                ('chances_pieces', models.TextField(verbose_name='Piezas o Partes Reemplazadas')),
                ('contractor', models.CharField(max_length=300, verbose_name='Contratista')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment', verbose_name='Equipo')),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
                'db_table': 'Maintenance',
            },
        ),
    ]
