# Generated by Django 4.1.4 on 2022-12-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_address_user_user_date_birth_academictraining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academictraining',
            name='date_graduation',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Graduación'),
        ),
    ]
