# Generated by Django 4.1.4 on 2022-12-14 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_academictraining_date_graduation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academictraining',
            options={'verbose_name': 'AcademicTraining', 'verbose_name_plural': 'AcademicTrainings'},
        ),
        migrations.AlterField(
            model_name='academictraining',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AlterModelTable(
            name='academictraining',
            table='AcademicTraining',
        ),
    ]
